blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions & Questions
    url: https://github.com/Q300Z/dynamic-day-night-wallpaper/discussions
    about: Posez vos questions et échangez avec la communauté.
  - name: 📖 Site officiel & Documentation
    url: https://qalpuch.cc
    about: Consultez les informations officielles et notes de version.
